target_column: "target"
to_feature_store: True
test_fraction: 0.2
random_state: 42
run_name: "full_project"
use_feature_selection: False
feature_selection: "rfe"
model_name: "jobchange"
baseline_model_params:
  solver: 'lbfgs'
  penalty: 'l2'
  max_iter: 100
  l1_ratio: 0.0
  C: 1438.44988828766
  random_state: 42
  class_weight: 'balanced'