target_column: "target"
to_feature_store: True
test_fraction: 0.2
random_state: 42
run_name: "full_project"
use_feature_selection: False
feature_selection: "rfe"
model_name: "jobchange"
baseline_model_params:
  n_estimators: 100
  max_depth: 6
  max_features: 20
  random_state: 2021