target_column: "target"
to_feature_store: True
test_fraction: 0.2
random_state: 42
run_name: "full_project"
use_feature_selection: False
feature_selection: "rfe"
model_name: "jobchange"
baseline_model_params:
  solver: 'lbfgs'
  penalty: 'l2'
  max_iter: 100
  l1_ratio: 0.0
  C: 1438.44988828766
  random_state: 42
  class_weight: 'balanced'
hyperparameters:
  LogisticRegression:
    solver: ['liblinear', 'lbfgs']
    C: [0.01, 0.1, 1, 10]
    max_iter: [100, 200, 300]
  GradientBoostingClassifier:
    n_estimators: [100, 200, 300, 400]
    learning_rate: [0.01, 0.1, 0.2, 0.3]
    max_depth: [3, 4, 5, 6]
    subsample: [0.6, 0.7, 0.8, 0.9, 1.0]